src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/dto/request/MateCreateRequest.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/mate/entity/Mate.java, src/main/java/org/swyp/dessertbee/mate/entity/MateCategory.java, src/main/java/org/swyp/dessertbee/mate/entity/MateMember.java, src/main/java/org/swyp/dessertbee/mate/entity/MateStatistics.java, src/main/java/org/swyp/dessertbee/mate/entity/SavedMate.java, src/main/java/org/swyp/dessertbee/mate/repository/MateCategoryRepository.java, src/main/java/org/swyp/dessertbee/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java
> 8
> 디저트메이트 엔터디,dto 구현
> 디저트메이트 생성 api 구현 (아직 멤버 신청 부분 만들지 않아서 인원 제한 로직 없음 추후 만들 예정)
> 디저트메이트 상세 조회 api 구현
> 테스트코드를 작성하다가 테스트 코드에서 버그가 나서 빼고 postman으로 테스트 했습니다.
> 확인 후 피드백 부탁드립니다!
=> 디저트메이트 생성, 상세 조회 api 구현

.gitignore, src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/controller/OAuth2Controller.java, src/main/java/org/swyp/dessertbee/auth/dto/login/LoginRequest.java, src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java, src/main/java/org/swyp/dessertbee/auth/dto/logout/LogoutRequest.java, src/main/java/org/swyp/dessertbee/auth/dto/logout/LogoutResponse.java, src/main/java/org/swyp/dessertbee/auth/dto/passwordreset/PasswordResetRequest.java, src/main/java/org/swyp/dessertbee/auth/dto/signup/SignUpRequest.java, src/main/java/org/swyp/dessertbee/auth/dto/signup/SignUpResponse.java, src/main/java/org/swyp/dessertbee/auth/exception/AuthExceptions.java, src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java, src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java, src/main/java/org/swyp/dessertbee/auth/oauth2/CustomSuccessHandler.java, src/main/java/org/swyp/dessertbee/auth/repository/AuthRepository.java, src/main/java/org/swyp/dessertbee/auth/service/AuthService.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/CustomOAuth2UserService.java, src/main/java/org/swyp/dessertbee/auth/service/TokenService.java, src/main/java/org/swyp/dessertbee/config/SecurityConfig.java, src/main/java/org/swyp/dessertbee/user/dto/UserDTO.java, src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java, src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java
#17 
- JWT 로그인 구현
- KeepLoggedIn True일 시, (액세스 토큰 기본 1일 -> 3일, 리프레시 토큰 기본 10일 -> 30일)
- JWT 회원가입 구현
- 로그아웃 구현
- 액세스 토큰은 프론트에서 무효화
- 리프레시 토큰 무효화는 DB에서 진행
=> [Feature] JWT관련 로그인, 회원가입, 로그아웃, 비밀번호 변경 구현 #21

src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateMemberController.java, src/main/java/org/swyp/dessertbee/mate/dto/request/MateCreateRequest.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateMemberResponse.java, src/main/java/org/swyp/dessertbee/mate/entity/Mate.java, src/main/java/org/swyp/dessertbee/mate/entity/MateMember.java, src/main/java/org/swyp/dessertbee/mate/entity/MateMemberGrade.java, src/main/java/org/swyp/dessertbee/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java
> 28
> 디저트 메이트 생성 시 메이트 멤버 테이블에 생성자 등록
> 디저트 메이트 삭제 시 해당 메이트 멤버 데이터 삭제(soft delete 적용)
> 현재 uuid를 통해 프론트와 데이터 주고 받고 있는데 괜찮게 짜여진건지 확인 후 피드백 부탁드립니다!
=> 디저트 메이트 멤버 관련 로직 추가

src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateMemberController.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java
> 32
> 디저트 메이트 리스트 전체 조회
> 디저트 메이트 상세 보기 데이터 닉네임 추가
> 범위 설정 잘못하면 예외처리 뜨게 만들었습니다.
> 혹시 더 예외처리 해야할 부분들이 있는지 한번만 봐주실 수 있나용?
=> [Feature] 디저트 메이트 전체 조회 api 구현

src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java, src/main/java/org/swyp/dessertbee/auth/oauth2/CustomSuccessHandler.java, src/main/java/org/swyp/dessertbee/auth/service/AuthService.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/common/service/ImageService.java, src/main/java/org/swyp/dessertbee/config/CorsMvcConfig.java, src/main/java/org/swyp/dessertbee/config/SecurityConfig.java, src/main/java/org/swyp/dessertbee/user/controller/UserController.java, src/main/java/org/swyp/dessertbee/user/dto/ProfileImageUpdateRequestDto.java, src/main/java/org/swyp/dessertbee/user/dto/UserDetailResponseDto.java, src/main/java/org/swyp/dessertbee/user/dto/UserOAuthDto.java, src/main/java/org/swyp/dessertbee/user/dto/UserResponseDto.java, src/main/java/org/swyp/dessertbee/user/dto/UserUpdateRequestDto.java, src/main/java/org/swyp/dessertbee/user/entity/MbtiEntity.java, src/main/java/org/swyp/dessertbee/user/entity/NicknameValidationPurpose.java, src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java, src/main/java/org/swyp/dessertbee/user/service/UserService.java, src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
#42 
- 유저 회원가입 시 프로필 이미지 multipart/form-data로 받기 -> 따로 프로필만 수정하는 것으로 변경
- 유저 회원 정보 업데이트 시 이미지 multipart/form-data로 받기 -> 따로 프로필만 수정하는 것으로 변경
- uploadAndSaveImage 에 에러 핸들링 추가
- OAuth 로그인 후 리다이렉트 하도록 설정(쿠키 포함)
- CORS 설정 추가
=> [Feature] 유저 프로필 이미지

src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateMemberController.java, src/main/java/org/swyp/dessertbee/mate/dto/MateUserIds.java, src/main/java/org/swyp/dessertbee/mate/exception/MateExceptions.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java
> 46
> 디저트 메이트 기능(댓글, saved 기능 제외) 현재까지 나온 api 들 에러 핸들링
> 더 추가해야할 예외들이 있을까요?
=> [Refactor] 디저트메이트 에러 핸들링 추가

src/main/java/org/swyp/dessertbee/auth/dto/signup/SignUpRequest.java, src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java, src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/CustomOAuth2UserService.java, src/main/java/org/swyp/dessertbee/auth/service/TokenService.java, src/main/java/org/swyp/dessertbee/role/entity/RoleEntity.java, src/main/java/org/swyp/dessertbee/role/entity/RoleType.java, src/main/java/org/swyp/dessertbee/role/repository/RoleRepository.java, src/main/java/org/swyp/dessertbee/role/service/RoleService.java, src/main/java/org/swyp/dessertbee/role/service/UserRoleService.java, src/main/java/org/swyp/dessertbee/seeder/RoleSeeder.java, src/main/java/org/swyp/dessertbee/user/controller/UserController.java, src/main/java/org/swyp/dessertbee/user/dto/UserDetailResponseDto.java
#49 
- 토큰 만료 및 생성 관련 시간대를 한국 서울 기준으로 수정함.
- Authorization Bearer 토큰 request Header 대문자 소문자 처리하도록 수정
- ROLE 역할에 따른 다른 ROLE의 부여 (기본은 ROLE_USER) 바디값을 통해 받도록 수정
- isPreferencesSet = true or false 로 바디값을 통해서 보내서 취향 설정 여부를 손쉽게 파악 가능
=> [FIX] 리프레시 토큰 만료시간 설정

src/main/java/org/swyp/dessertbee/store/review/repository/StoreReviewRepository.java, src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/HolidayResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/OperatingHourResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreSummaryResponse.java, src/main/java/org/swyp/dessertbee/store/store/repository/SavedStoreRepository.java, src/main/java/org/swyp/dessertbee/store/store/repository/UserStoreListRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java, src/main/java/org/swyp/dessertbee/store/store/service/UserStoreService.java, src/main/java/org/swyp/dessertbee/user/controller/UserController.java, src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
> #60 
> StoreSummaryResponse 응답 객체 수정
> HolidayResponse, OperatingHourResponse 응답 객체 별도로 정의
> 해당 가게를 저장한 사람들의 취향 태그 Top3 조회
> 리뷰 조회 시 삭제된 리뷰를 제외 (deletedAtisNull 조건 추가)
> 가게 저장 리스트 및 가게 추가 중복 예외처리
> 사용자 선호도 수정 및 저장한 가게 취향 수정 API 구현
> 가게 간략 정보 조회 API 수정 (영업정보, 사장님픽 이미지, 취향 태그 Top3)
=> [FIX] 가게 간략 정보 조회 API 수정

src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateReplyController.java, src/main/java/org/swyp/dessertbee/mate/dto/request/MateReplyCreateRequest.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateReplyPageResponse.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateReplyResponse.java, src/main/java/org/swyp/dessertbee/mate/entity/MateReply.java, src/main/java/org/swyp/dessertbee/mate/entity/MateStatistics.java, src/main/java/org/swyp/dessertbee/mate/exception/MateExceptions.java, src/main/java/org/swyp/dessertbee/mate/repository/MateReplyRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateReplyService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
> 58
> 디저트메이트 댓글 생성 API 구현
> 디저트메이트 댓글 조회(한개만) API 구현
> 디저트메이트 댓글 전체 조회 API 구현
> 디저트메이트 댓글 삭제 API 구현
> 디저트메이트 댓글 수정 API 구현
=> [Feature] 디저트 메이트 댓글 API 구현

src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateResponse.java, src/main/java/org/swyp/dessertbee/mate/entity/Mate.java, src/main/java/org/swyp/dessertbee/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/store/menu/service/MenuService.java, src/main/java/org/swyp/dessertbee/store/review/dto/response/StoreReviewResponse.java, src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/request/StoreCreateRequest.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java, src/main/java/org/swyp/dessertbee/store/store/entity/Store.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java, src/main/java/org/swyp/dessertbee/store/store/service/UserStoreService.java
> #74 
> description(가게 소개) 추가
> 해당 가게를 저장한 사람들의 취향 태그 Top3 조회
> 한줄리뷰: 닉네임, 프로필 이미지, 리뷰 갯수 포함
> 가게에 해당하는 디저트메이트 모임 조회
> 가게 상세 정보 조회 API 수정
> Store 관련 공통 에러코드 정리 -> ErrorCode
=> [Fix] 가게 상세 정보 조회 api 수정

src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/service/AuthService.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
#80 
- 회원가입 시 로그인 응답과 동일하게 변경
- 회원가입 시 로그인을 하지 않아도 됨.
- CORS 설정 모든 origin 허용으로 변경(임시적)
=> refactor : 회원가입 시 로그인 응답과 동일하게 변경

src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/preference/repository/PreferenceRepository.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/entity/StoreHoliday.java, src/main/java/org/swyp/dessertbee/store/store/entity/StoreOperatingHour.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
> #79 
> 반경 내 가게 조회 시 요청값에 태그를 포함할 수 있도록 수정
> 태그가 포함된 요청일 경우 "반경 내 가게를 저장한 사용자들의 취향 태그 Top3 중 하나가 태그와 일치하는 가게만 조회"하는 조건 추가
> 태그가 포함되지 않은 요청일 경우 "반경 내 모든 가게 조회"
> 인증된 사용자가 /api/stores/map/my-preferences로 요청을 보낼 경우, "반경 내 해당 사용자의 취향 태그 중 하나라도 일치하는 가게를 조회"
> 인증되지 않은 사용자의 요청은 예외처리
> 취향 관련 ErrorCode 추가
> 조회 쿼리 작성
> 인증되지 않은 사용자일 경우
=> [FEATURE] 지도 반경 내 태그 필터링된 가게 조회 api

src/main/java/org/swyp/dessertbee/common/service/ImageService.java, src/main/java/org/swyp/dessertbee/common/util/CustomMultipartFile.java, src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java, src/main/java/org/swyp/dessertbee/store/menu/dto/request/MenuCreateRequest.java, src/main/java/org/swyp/dessertbee/store/menu/service/MenuService.java
> #89 
> CustomMultipartFile 클래스 생성하여 파일이름 사용자화
> 메뉴 리스트를 인덱스로 매핑하여 각 메뉴 이름으로 파일 이름을 바꿔 이미지 업로드/저장
> 가게 등록 시 각 메뉴별 이미지 업로드 테스트 (이미지가 있을 경우 menu 객체 안에 imageFileKey 포함하여 요청 보낼 것)
> ImageService uploadAndSaveImage() 리턴값 void로 변경
=> [Fix] 메뉴 리스트 등록 시 이미지 매핑 오류 해결

src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/UserStoreListSimpleResponse.java, src/main/java/org/swyp/dessertbee/store/store/repository/SavedStoreRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java, src/main/java/org/swyp/dessertbee/store/store/service/UserStoreService.java, src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java
> #95 
> 유저가 저장한 가게인지 여부 추가
> 저장 리스트 id 추가
> user uuid_to_bin 변환 메서드 추가 (가게 등록 service)
> listId로 리스트 정보 조회 api 구현
=> [FIX] 가게 상세정보 조회 api 수정

src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/dto/TokenResponse.java, src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java, src/main/java/org/swyp/dessertbee/auth/service/AuthService.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/TokenService.java, src/main/java/org/swyp/dessertbee/common/util/CookieUtil.java
#99 
리프레시 토큰관련해서 기존 전달방식에 대한 수정
- 기존 : 서버측에서만 저장
- 변경 : 클라이언트측으로 헤더 쿠키에 넣어서 전달
관련 api
- 액세스 토큰 갱신
- 로그인
- 회원가입
=> [Fix] 리프레시 토큰 전달 방식 수정

src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java, src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
#105
유저 취향관련 설정 함수 분리
예림님 해당 함수로 처리 가능하신가요?
혹은 업데이트 취향 관련해서 더 분리를 진행해볼까요?
=> [REFACTOR] 유저 취향관련 설정 함수 분리

src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java, src/main/java/org/swyp/dessertbee/store/store/service/UserStoreService.java, src/main/java/org/swyp/dessertbee/user/controller/UserController.java
> #107 
> 유저의 선호도 정보 수정 후, 유저가 저장한 가게의 선호도 정보를 업데이트하는 로직 추가
=> [FIX] 유저가 저장한 가게의 선호도 정보를 업데이트

src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateMemberController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateReplyController.java, src/main/java/org/swyp/dessertbee/mate/controller/SavedMateController.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/mate/entity/Mate.java, src/main/java/org/swyp/dessertbee/mate/entity/MateApplyStatus.java, src/main/java/org/swyp/dessertbee/mate/entity/MateMember.java, src/main/java/org/swyp/dessertbee/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/mate/service/SavedMateService.java
> 71
> 디저트메이트 필터링, 검색 api 구현(전체 조회 api 수정)
> 디저트메이트 applyStatus 필드 추가
> 디저트메이트 전채 조회 시 saved 필드 추가
> 디저트메이트 신청 취소 api 구현
> 신청 대기,거절 엔드포인트 변경
> 디저트메이트 내가 참여한 디저트메이트 조회 api 구현
> 이번에 변경 된 부분들이 좀 많습니다. 보시다가 이해 안되는 부분들은 편하게 물어봐주세요!
> 디저트메이트 부분만 보시면 될 거 같습니다!
=> [Feature] 디저트메이트 필터링 및 검색 api 구현

src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java, src/main/java/org/swyp/dessertbee/auth/jwt/JwtAuthenticationEntryPoint.java, src/main/java/org/swyp/dessertbee/common/exception/GlobalExceptionHandler.java, src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
#98 
- 인증이 필요한 곳에 토큰이 없다면 401 에러
- enum 값이 제대로 안들어 온 것 처리 잘못된 값 입력 400 에러
추후에 경로를 구체적으로 제한할 것인데 일단 테스트 용이성을 위해서 인증이 필요없도록 처리할 엔드포인트를 정의해주세요!
=> [FEATURE] 토큰 및 http 파싱시 에러 처리

src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java, src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java
#121 
로그인 응답에 isPreferenceSet을 반환 작업을 했습니다.
일반 로그인, 회원가입
카카오 로그인, 회원가입에 isPreferenceSet을 반환합니다.
=> feat : 로그인 응답에 isPreferenceSet을 반환

src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
#124 
쿠키로 전달하던 리프레시 토큰을 바디값으로 전달하였습니다.
- 카카오로그인
- 일반 로그인
- 일반 회원가입
=> refactor: 쿠키로 전달하던 리프레시 토큰을 바디값으로 전달

src/main/java/org/swyp/dessertbee/mate/dto/response/MateResponse.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
> #129 
> 가게 상세에서 디저트메이트 탭 조회 시 저장 유무를 응답값으로 추가했습니다.
=> [FEATURE] 가게 상세 디저트메이트 saved(저장 유무) 추가

build.gradle, src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java, src/main/java/org/swyp/dessertbee/auth/service/AuthService.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java, src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java, src/main/java/org/swyp/dessertbee/common/service/ImageService.java
#127 
- 첫 카카오 회원가입 시 만약 카카오 프로필 이미지가 전달되었다면 
- 카카오 프로필 이미지 등록
- 이미 동일한 이메일로 카카오 가입 시에는 유효하지 않게 처리
- 외부 url을 통한 s3 등록 함수 구현 
이미지 등록이 되는 것을 확인
=> [FEATURE] 카카오 프로필 이미지 등록

src/main/java/org/swyp/dessertbee/config/SecurityConfig.java, src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java, src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java
> #139 
> 가게, 메뉴, 한줄리뷰 등록/수정/삭제 api에 @PreAuthorize 어노테이션을 적용해 역할 권한을 검증합니다.
권한이 없는 사용자로 메서드 실행 시 Access Denied 오류
=> [FIX] 가게 api @PreAuthorize 적용

src/main/java/org/swyp/dessertbee/auth/dto/userdetails/CustomUserDetails.java, src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java, src/main/java/org/swyp/dessertbee/auth/service/CustomUserDetailsService.java, src/main/java/org/swyp/dessertbee/config/SecurityConfig.java, src/main/java/org/swyp/dessertbee/role/entity/RoleEntity.java, src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
> #168 
> email을 Principal로 넣지 않고, DB에서 UserEntity를 조회하여 Principal로 설정
> UserEntity를 UsernamePasswordAuthenticationToken에 설정하여, 이후 SecurityContextHolder에서 UserEntity를 직접 가져올 수 있도록 함
> authentication.getPrincipal()이 UserEntity인지 확인 후 반환
=> [FIX]  getCurrentUser() 메서드 버그 수정

src/main/java/org/swyp/dessertbee/community/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/community/review/controller/ReviewController.java
> 175
> keyword=%ED%99%8D%EB%8C%80 이런 형식으로 넘어오던 한글 decode해서 검색 되도록 수정
=> [FIX] encode되서 넘어오는 한글 검색 가능하도록 수정

src/main/java/org/swyp/dessertbee/auth/dto/userdetails/CustomUserDetails.java, src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java, src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/CustomUserDetailsService.java, src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java, src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
#179 
- 토큰 페이로드 구성 메서드를 캡슐화 적용
- 토큰 페이로드에 userUuid 삽입
- 관련 서비스 메서드에도 동일하게 적용
- 변경이 힘들어지네요. 뭔가 코드 구조를 객체지향적으로 바꾸어야...ㅠ
=> [FEATURE] userUuid를 토큰 payload에 삽입

src/main/java/org/swyp/dessertbee/community/review/dto/response/ReviewSummaryResponse.java, src/main/java/org/swyp/dessertbee/community/review/repository/ReviewRepository.java, src/main/java/org/swyp/dessertbee/config/SecurityConfig.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
> #192 
> 가게 상세정보에서 보여질 간략한 커뮤니티 리뷰 응답 dto 생성 
> 썸네일 - ReviewContent의 type="image"인 첫번째 값
> 내용 - ReviewContent의 type="text"
> 그 외 - reviewUuid, userUuid, nickname, profileImage, title, createdAt, updatedAt
> SecurityConfig에서 Swagger 관련 경로 허용
=> [FEATURE] 가게 상세 정보 커뮤니티 리뷰 조회

src/main/java/org/swyp/dessertbee/common/controller/SearchController.java, src/main/java/org/swyp/dessertbee/common/entity/UserSearchHistory.java, src/main/java/org/swyp/dessertbee/common/repository/UserSearchHistoryRepository.java, src/main/java/org/swyp/dessertbee/common/service/SearchService.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java, src/main/java/org/swyp/dessertbee/store/store/service/UserStoreService.java, src/main/java/org/swyp/dessertbee/user/service/UserService.java
> #194 
> 인증된 사용자가 가게 검색 시 최근 검색어를 최대 10개까지 저장합니다.
> 유저별 최대 10개까지 검색어 저장 (초과 시 예전 검색어부터 삭제)
> 동일 검색어 저장 x (추가 커밋: 테스트 시 "디저트 ", "디저트" 다른 단어로 인식되는 문제 해결 -> 마지막 공백만 제거 )
> 인증된 사용자의 id와 함께 저장
> 최신(생성일 desc)순으로 조회
> 기존에 UserServiceImpl의 getCurrentUser() 호출하는 부분 수정 (인터페이스 코드 추가)
=> [FEATURE] 유저 별 최근 검색어 저장, 조회 api

build.gradle, src/main/java/org/swyp/dessertbee/DessertBeeApplication.java, src/main/java/org/swyp/dessertbee/common/controller/SearchController.java, src/main/java/org/swyp/dessertbee/common/dto/PopularSearchResponse.java, src/main/java/org/swyp/dessertbee/common/entity/PopularSearchKeyword.java, src/main/java/org/swyp/dessertbee/common/repository/PopularSearchKeywordRepository.java, src/main/java/org/swyp/dessertbee/common/service/SearchService.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyService.java, src/main/java/org/swyp/dessertbee/community/mate/service/SavedMateService.java, src/main/java/org/swyp/dessertbee/config/RedisConfig.java, src/main/java/org/swyp/dessertbee/store/review/repository/StoreReviewRepository.java, src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java, src/main/resources/application.yml
> #196 
> 실시간 인기 검색어 기능 개선 및 데이터 동기화 로직 추가
> MySQL 동기화 로직 개선
> 1분마다 Redis 데이터를 MySQL과 동기화 (syncPopularSearchesToDB)
> 동기화 후 현재 검색어 데이터를 SYNCED_POPULAR_SEARCH_KEY에 저장하여 비교 가능하도록 개선
> 자정마다 MySQL로 데이터 이전 후 Redis 초기화
> Redis 인기 검색어 초기화 API 추가 (테스트용)
=> [FEATURE] 실시간 인기검색어 저장, 동기화, 조회 API

src/main/java/org/swyp/dessertbee/common/controller/SearchController.java, src/main/java/org/swyp/dessertbee/common/dto/UserSearchHistoryDto.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/common/repository/UserSearchHistoryRepository.java, src/main/java/org/swyp/dessertbee/common/service/SearchService.java, src/main/java/org/swyp/dessertbee/store/review/repository/StoreReviewRepository.java, src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/SavedStoreResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreListLocationResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreMapResponse.java, src/main/java/org/swyp/dessertbee/store/store/repository/SavedStoreRepository.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreTagRelationRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java, src/main/java/org/swyp/dessertbee/store/store/service/UserStoreService.java
> #202 
> 최근 검색어 조회용 dto 생성 (id, 검색날짜 포함)
> 유저별 최근 검색어 개별 삭제 api
> 유저별 최근 검색어 전체 삭제 api
> 저장된 가게 리스트 위도, 경도 필드 추가
> 반경 내 가게 검색 api 응답 데이터 추가 -> operatingHours, totalReviewCount, tags, storeImages(중 첫번째)
> 저장 리스트 내 가게들의 위도, 경도 조회 api 추가
=> [FEATURE] 유저별 최근 검색어 삭제 API 구현 (+etc)

src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/common/annotation/ApiErrorResponses.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/common/service/ImageService.java, src/main/java/org/swyp/dessertbee/config/SwaggerErrorResponseCustomizer.java, src/main/resources/application-prod.yml
#215 
- 에러 코드를 통해서 스웨거에 에러 문서를 삽입할 수 있도록 `ApiErrorResponses ` 생성, `SwaggerErrorResponseCustomizer` 생성
- 이미지 에러 처리 추가 `getImagesByTypeAndId`
- 스웨거 문서에 에러 처리하는 방법에 대해서 의문이 있으시다면 알려주세요!
=> [DOCS] 스웨거 인증 에러 코드 추가

src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java, src/main/java/org/swyp/dessertbee/auth/exception/AuthExceptions.java, src/main/java/org/swyp/dessertbee/auth/exception/OAuthExceptions.java, src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java, src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
#215 
- OAuth 에러 코드 검토 및 정리
- Swagger 문서에 OAuth 등록 
- Auth Controller에서 쓸모없는 import 제거 및 코드 정리
=> [DOCS] Oauth 스웨거 문서 적용 

.github/workflows/deploy.yml, Dockerfile, build.gradle, docker-compose.prod.yml, src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
#171 
- 기존 systemd + JAR 배포에서 Docker 기반 배포 방식으로 전환
- Gradle 빌드 → Docker 이미지 빌드 & 푸시 → EC2 배포
- .env 파일은 GitHub Secrets(ENV_PROD)에서 자동 생성
- EC2에선 docker-compose.prod.yml로 앱 + Redis 컨테이너 실행
- 도커/컴포즈 구성 방식에서 개선점 있으면 피드백 부탁드립니다.
- workflow의 처리나 배포 과정 중 불필요한 부분이 있을까요?
=> [CHORE] 도커 세팅 

nginx/conf/default.conf.template, src/main/resources/application.yml
- 엔진엑스에 스웨거 문서 경로 추가
- paths-to-match 설정 추가
=> [HOTFIX] 엔진엑스 설정에 스웨거 문서 경로 명시적 허용

nginx/conf/default.conf.template, src/main/java/org/swyp/dessertbee/config/SwaggerConfig.java
- 엔진엑스 스웨거 설정 제거
- swagger config 에서 기존 prod 환경에서 작동하던 주소를 release용으로 변경
=> chore : 엔진엑스 스웨거 경로 제거, 스웨거 config에 prod 경로 대신 release경로 대치

src/main/resources/application.yml
- api-docs로 요청해도 -> api-docs/ 로 뒤에 슬래쉬를 강제로 달아버림.
- yml 설정에서 api-docs를 호출하도록 명시
=> fix : trailing slash가 /api-docs 에러 해결

nginx/conf/default.conf.template
#245 
- Nginx `default.conf.template`에서 `if` + `set` 구조를 제거하고 `map` 지시어로 변수 정의하도록 변경
- `$cookie_deviceId`, `$http_authorization` → `$device_id`, `$auth_header` 로 안전하게 매핑
- `proxy_set_header` 사용 시 런타임 오류 방지
- `docker-compose up` 시 Nginx 설정 파일 오류로 인한 컨테이너 비정상 종료 해결
https://dwaejinho.tistory.com/entry/Nginx-%EC%95%85%EB%A7%88%EC%9D%98-IF-Dont-try-if-at-home
=> [FIX] 엔진엑스 변수 할당 방식 변경

src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java, src/main/java/org/swyp/dessertbee/auth/dto/TokenResponse.java, src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java, src/main/java/org/swyp/dessertbee/auth/entity/AuthEntity.java, src/main/java/org/swyp/dessertbee/auth/exception/AuthExceptions.java, src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java, src/main/java/org/swyp/dessertbee/auth/repository/AuthRepository.java, src/main/java/org/swyp/dessertbee/auth/service/AuthService.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java, src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java, src/main/java/org/swyp/dessertbee/auth/service/TokenService.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/common/util/CookieUtil.java, src/main/java/org/swyp/dessertbee/config/SecurityConfig.java, src/main/java/org/swyp/dessertbee/preference/controller/PreferenceController.java, src/main/java/org/swyp/dessertbee/user/controller/MbtiController.java
#227 
- 로그아웃 
- 디바이스 ID 를 명시하지 않았다면 모든 기기의 리프레시 토큰 비활성화
- JWT 필터를 통해 모든 기기의 리프레시 토큰이 비활성화 되어 있다면 현재 로그인 된 유저의 액세스 토큰이 만료되지 않았더라도 401 에러
- 디바이스 ID 를 명시한다면 해당 디바이스 ID의 리프레시 토큰만 비활성화, 액세스 토큰은 해당 다비이스의 클라이언트에서 무효화 실시
- 로그인 
- 로그인 시 디바이스 ID를 전달받지 못한다면 서버에서 생성 후 발급, 
- 로그인 시 디바이스 ID를 전달받았다면 해당 디바이스의 리프레시 토큰 갱신
- 토큰 갱신
- 무조건 특정 디바이스 ID를 명시해야 토큰 갱신 가능 
- 디바이스 ID를 명시하지 않으면 400 에러처리
=> [FIX] 디바이스 ID 발급을 통한 토큰 갱신 에러 처리

build.gradle, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/community/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateCreateRequest.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/community/mate/entity/Mate.java, src/main/java/org/swyp/dessertbee/community/mate/exception/MateExceptions.java, src/main/java/org/swyp/dessertbee/community/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateMemberServiceImpl.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java, src/main/java/org/swyp/dessertbee/config/SwaggerConfig.java
> 292
> 디저트메이트 생성 시 인원 제한 기능 추가
> 멤버 수락 시 수용 인원만큼 모으면 바로 모집 마감 되도록 수정
> 멤버 강퇴 시 수용 인원보다 적어지면 바로 모집 가능하도록 수정
> 웹,앱 버전 관리를 위해 스웨거 전역 Platform-Type 헤더 설정 추가
> 디저트메이트 생성 시 앱은 StoreId를 넘겨주고 웹은 장소명을 넘겨줘서 해당 값들로 서비스 내 가게 연결하도록 수정
> 헤더로 Platform-Type 넘어오는거 테스트로는 나눠져서 코드가 실행하는 걸 확인 했는데 혹시 각자 맡으신 부분에서 설정 오류가 생길 수도 있을 법한 곳 체크해주셨으면 좋겠습니다!
=> [Feature] 디저트메이트 인원 기능 추가 

nginx/conf/default.conf.template
#349 
엔진엑스에 deviceId 쿠키뿐만 아니라 
X-Device-ID 헤더에서 온 디바이스 아이디 또한 세팅할 수 있게 변경하였습니다.
이미 엔진엑스 설정을 릴리즈 서버에서 변경된 상태입니다. 
템플릿만 업데이트하여 후에도 적용되게 하였습니다.
=> [FIX] 토큰 갱신 오류 - 엔진엑스 deviceId 세팅

src/main/java/org/swyp/dessertbee/auth/service/CustomUserDetailsService.java
AuthenticationManager → AuthenticationProvider →
내부적으로 UserDetailsService#loadUserByUsername(username) 호출
동일 타입의 빈이 2개 이상 등록되어 있던 상태
- @Service로 하나 등록 (customUserDetailsService)
- @Bean으로 하나 등록 (userDetailsService)
경고 발생 
-> `Found 2 UserDetailsService beans, with names [customUserDetailsService, userDetailsService].`
userDetailsService 빈 하나만 등록하고 내부적으로 CustomUserDetailsService 인스턴스를 사용하도록 변경
=> [FIX] UserDetailsService 빈 중복 경고 

src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/store/review/exception/StoreReviewExceptions.java, src/main/java/org/swyp/dessertbee/store/review/repository/StoreReviewRepository.java, src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
> #362 
> 유저가 한 가게에 오늘 날짜로 작성한 리뷰가 이미 존재하면 예외를 던지도록 했습니다.
=> [CHORE] 동일 날짜 리뷰 등록 방지 예외처리 추가

src/main/resources/application-prod.yml, src/main/resources/application-release.yml
#381 
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.OAuth2AuthorizedClientManager]: Factory method 'getAuthorizedClientManager' threw exception with message: Error creating bean with name 'clientRegistrationRepository' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/client/servlet/OAuth2ClientRegistrationRepositoryConfiguration.class]: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception with message: redirectUri cannot be empty
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instanti …
```
=> [FIX&MERGE] redirect 경로 추가

src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateAppReplyResponse.java, src/main/java/org/swyp/dessertbee/community/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java, src/main/java/org/swyp/dessertbee/community/mate/service/SavedMateServiceImpl.java
> 387
> 내가 참여한 디저트메이트 조회 시 내가 작성한 게시글만 나오던 버그 참여하고 있는 모든 게시글 다 나오도록 수정
> 탈퇴한 회원의 게시글 조회 가능하도록 수정
> 탈퇴한 회원의 닉네임을 나중에 다른 사람이 이어서 쓰게 되면 조회 시 문제가 되지 않을까요?
> 나중엔 user에 deletedAt이 null 이 아닐 땐 닉네임 대신 탈퇴한 회원입니다로 나오게 하는게 좋은지 다른분들의 의견이 궁금합니다.
=> [FIX] 내 디저트메이트 조회 버그 및 탈퇴한 유저 목록 조회 버그 수정

src/main/java/org/swyp/dessertbee/admin/report/controller/MateReportAdminController.java, src/main/java/org/swyp/dessertbee/admin/report/dto/response/MateReplyReportCountResponse.java, src/main/java/org/swyp/dessertbee/admin/report/dto/response/MateReportCountResponse.java, src/main/java/org/swyp/dessertbee/admin/report/dto/response/ReportActionResponse.java, src/main/java/org/swyp/dessertbee/admin/report/service/MateReportAdminService.java, src/main/java/org/swyp/dessertbee/admin/report/service/MateReportAdminServiceImpl.java, src/main/java/org/swyp/dessertbee/admin/user/service/UserAdminService.java, src/main/java/org/swyp/dessertbee/admin/user/service/UserAdminServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java, src/main/java/org/swyp/dessertbee/auth/service/TokenService.java, src/main/java/org/swyp/dessertbee/common/aop/CheckWriteRestriction.java, src/main/java/org/swyp/dessertbee/common/aop/WriteRestrictionAspect.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/community/mate/repository/MateReportRepository.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyService.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyServiceImpl.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java, src/main/java/org/swyp/dessertbee/email/service/WarningMailService.java, src/main/java/org/swyp/dessertbee/email/service/WarningMailServiceImpl.java, src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java, src/main/resources/templates/mail/warning-email.html
> ex) 322
신고 처리 가이드 라인에 따른 구현
> 신고 처리 1단계 -  Mate 삭제, MateReply 삭제
> 신고 처리 2단계 - 작성자에게 경고 메일 발송
> 신고 처리 3단계(1) - 작성자 계정 정지 한달
> 신고 처리 3단계(2) - 작성 제한 7일
------
고민되는 점
신고된 Mate(댓글)에 대해서만 작성자에게 조치를 취해야할지.. 현재는 제한이 없는 상태.
1. 문제가 없는 Mate를 작성한 사용자에게 실수로 제한 할 수 있음
2. 수동 조치 프로세스이기 때문에 신고가 안되었더라도 중대한 문제라면 조치를 취해야하는 상황이 생길 수 있음
=> [REFACTOR] 관리자 신고 관리 기능 리팩토링

src/main/java/org/swyp/dessertbee/store/schedule/dto/HolidayResponse.java, src/main/java/org/swyp/dessertbee/store/schedule/entity/StoreHoliday.java, src/main/java/org/swyp/dessertbee/store/schedule/service/StoreScheduleServiceImpl.java, src/main/java/org/swyp/dessertbee/store/store/dto/request/BaseStoreRequest.java
> #417 
> 가게 휴무일 등록시 기존 일자별로 일일히 저장하던 방식에서 기간별(시작 날짜, 종료날짜)로 저장 및 조회하는 방식으로 변경했습니다.
=> [FIX] 가게 휴무일 등록 양식 수정

src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
> #429 
> 한줄리뷰 목록 조회 시 차단한 유저가 작성한 리뷰를 제외하도록 했습니다.
=> [FIX] 차단한 사용자가 작성한 한줄리뷰 필터링

.github/workflows/deploy.yml, docker-compose.yml, nginx/conf/default-http-only.conf.template, nginx/conf/default.conf.template, ssl/renew-ssl.sh, ssl/setup-ssl.sh, ssl/ssl-health-check.sh
#440 
- Let's Encrypt webroot 방식으로 첫 배포 시 자동 발급
- 매일 오전 3시, 오후 3시 자동 갱신 확인
- 만료 30일 이내 시에만 실제 갱신 수행
- nginx 무중단 재시작으로 서비스 영향 최소화
- SSL 인증서 만료일 및 상태 확인
```bash
ssl/
├── setup-ssl.sh           # 초기 SSL 인증서 발급
├── renew-ssl.sh           # 자동 갱신 및 cron 관리
└── ssl-health-check.sh    # SSL 상태 종합 모니터링
```
```bash
nginx/conf/
├── default.conf.template                # 정식 HTTPS 설정 (갱신 경로 포함)
└── default-http-only.conf.template      # 임시 HTTP 설정 (첫 배포용)
```
https://www.notion.so/SSL-1ff246cdb876809e9151efed17fc6b53?pvs=4
=> [FIX] 인증서 갱신 자동화 Flow

src/main/java/org/swyp/dessertbee/auth/dto/response/LoginResponse.java, src/main/java/org/swyp/dessertbee/auth/service/AppleOAuthService.java, src/main/java/org/swyp/dessertbee/auth/service/AuthService.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java, src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
- TokenResponse와 LoginResponse에 refreshExpiresIn 필드 추가
- TokenService.saveRefreshToken에 keepLoggedIn 파라미터 추가
#445 
TokenResponse와 LoginResponse에 refreshExpiresIn 필드 추가
- 클라이언트에서 리프레시 토큰의 만료시간을 알 수 있도록 개선
- 기존 expiresIn(액세스 토큰)과 함께 refreshExpiresIn(리프레시 토큰) 제공
- TokenService.saveRefreshToken에 keepLoggedIn 파라미터 추가
- DB 저장 시 keepLoggedIn 설정에 따른 올바른 만료시간 적용
- 기존: 항상 10일로 고정 → 변경: keepLoggedIn에 따라 10일/30일 구분
=> feat: 토큰 응답에 refreshExpiresIn 추가 및 keepLoggedIn 기반 DB 저장 구현

scripts/health-check.sh, src/main/java/org/swyp/dessertbee/auth/repository/AuthRepository.java
- health-check.sh에서 --format "table {{.State}}" 에러 해결
- Docker Compose v2.18.1에서 지원하지 않는 --format 옵션을 텍스트 파싱 방식으로 변경
=> [MERGE] Docker Compose --format 옵션 호환성 문제 해결 

src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/dto/request/PasswordResetRequest.java, src/main/java/org/swyp/dessertbee/auth/dto/response/PasswordResetResponse.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
#455 
-  불필요한 현재 비밀번호 필드를 제거, 비밀번호 확인 검증 로직을 추가
- PasswordResetResponse에 status, timestamp 필드 추가 응답 구조 표준화
- API 문서에 PASSWORD_MISMATCH 에러 케이스 추가
=> [FIX] reset password request dto update
