src/main/java/org/swyp/dessertbee/common/service/ImageService.java, src/main/java/org/swyp/dessertbee/common/service/S3Service.java, src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/entity/Mate.java, src/main/java/org/swyp/dessertbee/mate/repository/MateCategoryRepository.java, src/main/java/org/swyp/dessertbee/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java
> 13
> 디저트메이트 삭제 api 구현(파일 삭제 포함)
> s3 버킷 내 이미지 삭제 코드 수정
> url을 substring으로 잘랐는데 혹시 더 좋은 방법이 있을까요?
=> 디저트메이트 삭제 API 구현

src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/entity/Mate.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java
> 18
> 디저트메이트 모임 수정 API 구현
> DB 뿐만 아니라 S3에도 이미지가 수정되었습니다.
=> 디저트메이트 수정 api 구현

src/main/java/org/swyp/dessertbee/preference/repository/PreferenceRepository.java, src/main/java/org/swyp/dessertbee/seeder/MbtiSeeder.java, src/main/java/org/swyp/dessertbee/seeder/PreferenceSeeder.java, src/main/java/org/swyp/dessertbee/seeder/RoleSeeder.java, src/main/java/org/swyp/dessertbee/user/entity/MbtiEntity.java, src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java, src/main/java/org/swyp/dessertbee/user/repository/MbtiRepository.java
#27 
- 취향 데이터 시딩 파일추가
- mbti 데이터 시딩 파일추가
- 유저 테이블과 관계 추가
- 예림님이 데이터 올려달라고 하셔서 일단 먼저 푸시합니다!
=> [Feature] Data Seeding

src/main/java/org/swyp/dessertbee/mate/controller/MateMemberController.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateMemberResponse.java, src/main/java/org/swyp/dessertbee/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java
> 34
> 디저트메이트 멤버 전체 조회 api
> 디저트메이트 신청 api
> 디저트메이트 멤버 전체 조회
> 디저트메이트 신청 api (신청 시 approval_yn 은 false)
> approval_yn이 false 일때는 보이지 않음(위 사진은 approval_yn을 true로 변경한 사진)
=> 디저트메이트 신청 api

src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateMemberController.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java
> 39
> 디저트메이트 신청 수락 api 구현
> 디저트메이트 신청 거절 api 구현
=> [Feature] 디저트메이트 신청 수락 및 거절 api 구현 

src/main/java/org/swyp/dessertbee/common/entity/Image.java, src/main/java/org/swyp/dessertbee/common/entity/ImageType.java, src/main/java/org/swyp/dessertbee/common/service/ImageService.java, src/main/java/org/swyp/dessertbee/common/service/S3Service.java, src/main/java/org/swyp/dessertbee/seeder/StoreTagSeeder.java, src/main/java/org/swyp/dessertbee/store/menu/service/MenuService.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/request/StoreCreateRequest.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreSummaryResponse.java, src/main/java/org/swyp/dessertbee/store/store/entity/Store.java, src/main/java/org/swyp/dessertbee/store/store/entity/StoreHoliday.java, src/main/java/org/swyp/dessertbee/store/store/entity/StoreOperatingHour.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreHolidayRepository.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreOperatingHourRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
> #51 
> 가게 공지 컬럼 추가
> 가게 휴무일 및 영업시간 정보 entity, repository 구현
> 사장님 픽 이미지 업로드 추가
> 이미지 관련 코드 개선
> refType ENUM 값 추가 (OWNERPICK)
> Postman 가게 등록 api 테스트 (/api/stores)
=> 가게 등록 api 수정

src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateMemberController.java, src/main/java/org/swyp/dessertbee/mate/dto/request/MateCreateRequest.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateMemberResponse.java, src/main/java/org/swyp/dessertbee/mate/entity/Mate.java, src/main/java/org/swyp/dessertbee/mate/entity/MateMember.java, src/main/java/org/swyp/dessertbee/mate/entity/MateMemberGrade.java, src/main/java/org/swyp/dessertbee/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java
> 44
> 디저트 메이트 강퇴 api 개발 및 테스트 (생성자가 강퇴시킨 거)
> 디저트 메이트 모임 탈퇴 api 개발 및 테스트 (자발로 나간 거)
> 디저트 메이트 신청 시 상황에 따라 예외처리 되도록 수정
> IllegalArgumentException....예외처리 브랜치 따로 만들어서 해두겠습니다...그 부분은 넘어가주세요....ㅎ
=> 디저트 메이트 모임 나가기 관련 api 구현

src/main/java/org/swyp/dessertbee/preference/controller/PreferenceController.java, src/main/java/org/swyp/dessertbee/preference/dto/PreferenceResponseDto.java, src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java, src/main/java/org/swyp/dessertbee/user/controller/MbtiController.java, src/main/java/org/swyp/dessertbee/user/dto/MbtiResponseDto.java, src/main/java/org/swyp/dessertbee/user/service/MbtiService.java
#50 
- MBTI 아이디로 조회
- MBTI 타입으로 조회
- MBTI 전체 조회
- Preference 전체 조회
=> [FEATURE] MBTI, 선호도 관련 API 

src/main/java/org/swyp/dessertbee/store/event/controller/EventController.java, src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java, src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java, src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java
> #64 
> 수정 api Put->Patch로 통일
=> [CHORE] HTTP 메서드 타입 변경

src/main/java/org/swyp/dessertbee/common/controller/BannerClickController.java, src/main/java/org/swyp/dessertbee/common/entity/BannerClick.java, src/main/java/org/swyp/dessertbee/common/repository/BannerClickRepository.java, src/main/java/org/swyp/dessertbee/common/service/BannerClickService.java
> #77 
> 배너 클릭 시 횟수 카운팅 및 조회 기능
=> [FEAT] 배너 클릭 횟수 카운팅/조회 api 구현

src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
> #84 
> @PreAuthorize 컨트롤러에서 권한 체크
> 인증 여부 확인 조건 추가
=> [Refactor] 가게 등록 시 권한 처리

src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
> #85 
> 가게명, 가게태그, 주소, 메뉴명으로 가게 검색 (공백 무시, 문자만 체크)
=> [Feature] 가게 검색 api 구현

src/main/java/org/swyp/dessertbee/store/store/entity/Store.java, src/main/java/org/swyp/dessertbee/store/store/entity/StoreStatistics.java
> #89
> store_statistics 테이블의 storeId 컬럼명 store_id로 매핑
=> [FIX] db 매핑 컬럼명 수정

src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/UserStoreListResponse.java, src/main/java/org/swyp/dessertbee/store/store/service/UserStoreService.java
> #100 
> 제목그대로
> 이슈번호 100번이네요 아싸
=> [FIX] 리스트별 저장된 가게 조회 api 응답값 수정

src/main/java/org/swyp/dessertbee/preference/repository/PreferenceRepository.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
> #102 
> 취향 태그 필터링 요청값 수정 (id값 리스트)
=> [FIX] 가게 취향 태그 필터링 요청값 수정

src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java
> #113 
> 가게 상세 응답 dto에 latitude, longitude 필드 추가했습니다.
=> [CHORE] 위도, 경도 필드 추가

src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java, src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java
> #119 
> swagger 문서화를 위한 가게, 가게리뷰, 메뉴, 저장가게에 대한 api 설명을 작성했습니다.
=> [CHORE] API Operation 추가

src/main/java/org/swyp/dessertbee/common/entity/ReportCategory.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/common/repository/ReportRepository.java, src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateReplyController.java, src/main/java/org/swyp/dessertbee/mate/dto/request/MateReportRequest.java, src/main/java/org/swyp/dessertbee/mate/entity/Mate.java, src/main/java/org/swyp/dessertbee/mate/entity/MateReply.java, src/main/java/org/swyp/dessertbee/mate/entity/MateReport.java, src/main/java/org/swyp/dessertbee/mate/exception/MateExceptions.java, src/main/java/org/swyp/dessertbee/mate/repository/MateReportRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateReplyService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java
> 69
> 디저트메이트 신고 api 구현
> 디저트메이트 댓글 신고 api 구현
> 디저트메이트 모집마감 예외처리
=> [Feature] 디저트메이트, 댓글 신고 api 구현 

src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateReplyController.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateMemberResponse.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateReplyResponse.java
> 135
> 디저트메이트 ObjectMapper로 받던 것들 request 객체로 수정
> 디저트메이트 댓글 requestPart를 requestBody로 수정
=> [Fix]디저트메이트 ObjectMapper로 받던 것들 request 객체로 수정

src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java, src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java, src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java, src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/auth/service/TokenService.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorResponse.java, src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
#134 
- 토큰 리프레시 컨트롤러에서 쓸데없는 예외처리 제거
- JWT 필터 예외처리 적용
=> [FIX] 토큰 에러 처리 

src/main/java/org/swyp/dessertbee/mate/dto/response/MateReplyPageResponse.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateReplyResponse.java, src/main/java/org/swyp/dessertbee/mate/service/MateReplyService.java
> 138
> 디저트 메이트 전체 조회 시 총 갯수 필드 추가
> 디저트 메이트 createdAt, updatedAt 필드 추가
=> [Feature] 디저트메이트 댓글 갯수 필드 추가 

src/main/java/org/swyp/dessertbee/config/SecurityConfig.java, src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java, src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java, src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/SavedStoreResponse.java, src/main/java/org/swyp/dessertbee/store/store/entity/SavedStore.java, src/main/java/org/swyp/dessertbee/store/store/service/UserStoreService.java
> #143 
> SavedStore의 userPreferences 타입 변경 (List<String> -> List<Long>)
> 리스트에 가게 추가할 때 요청값으로 name 대신 id를 받음
=> [FIX] 리스트에 가게 추가 요청값 변경

src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreSummaryResponse.java
> #139 
> 반경 내 내취향 가게 조회 api 인증여부 체크
> StoreSummaryResponse에 description 필드 추가
=> [FIX] 가게 api 수정

.github/workflows/deploy.yml
#147 
- 워크플로우 트리거 설정 (데브, 메인)브랜치 푸시할 때
- 빌드는 깃허브 내에서 자르 파일만 전송
- 깃허브 내에 환경변수 설정 완료
-  EC2 인스턴스에서 배포 명령 스크립트 작성
- 기존 서비스 중지
- 데몬 리로드
- 애플리케이션 시작
- 서비스 상태 확인
- 부팅 시 서비스 자동시작 설정
파일 내용 한 번 확인해주세요~
=> feat : 깃허브 자동 배포 파일 설정

src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateMemberController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateReplyController.java, src/main/java/org/swyp/dessertbee/mate/controller/SavedMateController.java, src/main/java/org/swyp/dessertbee/mate/dto/request/MateApplyMemberRequest.java, src/main/java/org/swyp/dessertbee/mate/dto/request/MateRequest.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateReplyService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/mate/service/SavedMateService.java
> 138
> 디저트메이트 form-data requestBody로 수정
=> [FIX] 디저트메이트 requestBody로 수정 (form-data는 multipart 있을때만)

src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/common/exception/GlobalExceptionHandler.java
#150 
- 에러코드 추가 403
- ExceptionHandler 추가
예시테스트 해보기 위해서 프로필에 PreAuthorize 달고 테스트 했습니다!
=> feat : PreAuthorize 예외처리

src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateMemberController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateReplyController.java, src/main/java/org/swyp/dessertbee/mate/controller/SavedMateController.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateMemberResponse.java, src/main/java/org/swyp/dessertbee/mate/entity/MateApplyStatus.java, src/main/java/org/swyp/dessertbee/mate/entity/MateMember.java, src/main/java/org/swyp/dessertbee/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateReplyService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/mate/service/SavedMateService.java, src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java, src/main/java/org/swyp/dessertbee/user/service/UserService.java, src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
> ex)  158
> 디저트 메이트 rejected, banned enum 추가
> 디저트 메이트 bearerToken 으로 수정 
> 디저트 메이트 reponse String 이었던거 json 형식으로 변경
>
=> [Feature] 디저트 메이트 rejected, banned enum 추가...etc

src/main/java/org/swyp/dessertbee/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java, src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
> 155
> 현재 비로그인으로 들어오면 null로 되어 구동이 되지 않던 부분 null 처리하여 수정
>
=> 디저트메이트 사용자 없을 때 null 처리

src/main/java/org/swyp/dessertbee/mate/controller/MateReplyController.java, src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
> #163 
> ObjectMapper를 사용하지 않고 request 객체 그대로 요청값으로 사용하도록 변경
=> [FIX] 가게, 메뉴 등록 및 수정 시 매핑 방식 수정 (ObjectMapper 사용x)

src/main/java/org/swyp/dessertbee/common/service/ImageService.java, src/main/java/org/swyp/dessertbee/mate/controller/MateMemberController.java, src/main/java/org/swyp/dessertbee/mate/controller/MateReplyController.java, src/main/java/org/swyp/dessertbee/mate/controller/SavedMateController.java, src/main/java/org/swyp/dessertbee/mate/dto/request/MateApplyMemberRequest.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/mate/dto/response/MateMemberResponse.java, src/main/java/org/swyp/dessertbee/mate/service/MateMemberService.java, src/main/java/org/swyp/dessertbee/mate/service/MateReplyService.java, src/main/java/org/swyp/dessertbee/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/mate/service/SavedMateService.java
> 158
> 디저트메이트 @AuthenticationPrincipal 남아있는 코드 삭제 후 수정
> 디저트메이트 리스트 조회 코드 중복 되어있는 거 리팩토링
> 현재 bearer Token 이 가면 applyStatus 잘 넘어가도록 수정
=> 디저트메이트 리팩토링 및 중복 코드 삭제

src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java, src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
#165 
Auth 서비스에서 userRole service 코드를 사용하도록 변경했습니다.!
=> [REFACTOR] userRole service method apply

src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
=> [FIX] 반경 내 가게 검색시 키워드 디코딩

src/main/java/org/swyp/dessertbee/community/review/service/ReviewService.java
> 180
> 커뮤니티 리뷰 이미지 없으면 content 데이터 안들어가는 버그 수정
=> review 컨텐츠 안들어가는 버그 수정

src/main/java/org/swyp/dessertbee/community/review/dto/response/ReviewResponse.java, src/main/java/org/swyp/dessertbee/community/review/entity/ReviewStatistics.java, src/main/java/org/swyp/dessertbee/community/review/repository/ReviewStatisticsRepository.java, src/main/java/org/swyp/dessertbee/community/review/service/ReviewService.java
> 183
> 리뷰 상세 보기 페이지에 views (조회수) 추가
=> [Feature] review 상세 정보에 views 추가

src/main/java/org/swyp/dessertbee/community/mate/service/MateService.java
> 189
> 디저트메이트 장소로 가게 연결 되던거 위도 경도로 수정
=> [FIX]디저트메이트 위도경도 로직 추가

src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
- 인증이 필요하지 않은 경로 명확히 지정.
- 나머지는 인증이 필요함.
경로가 명확한지 다시 한 번 체크..부탁드려요
=> [FEATURE] SecurityConfig 경로 설정

src/main/java/org/swyp/dessertbee/community/review/repository/ReviewContentRepository.java, src/main/java/org/swyp/dessertbee/community/review/service/ReviewService.java, src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java, src/main/java/org/swyp/dessertbee/user/dto/response/UserDetailResponseDto.java, src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java, src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
#207 
의도적으로 취향 미설정 시 isPreferenceSet이 true나오도록 설정
- 유저 엔티티에 컬럼 추가
- dto 변경
=> [REFACTOR] 의도적인 취향 미설정 처리

src/main/java/org/swyp/dessertbee/common/entity/Image.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/common/repository/ImageRepository.java, src/main/java/org/swyp/dessertbee/common/service/ImageService.java, src/main/java/org/swyp/dessertbee/community/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/community/review/dto/ReviewContentDto.java, src/main/java/org/swyp/dessertbee/community/review/entity/ReviewContent.java, src/main/java/org/swyp/dessertbee/community/review/repository/ReviewContentRepository.java, src/main/java/org/swyp/dessertbee/community/review/repository/ReviewRepository.java, src/main/java/org/swyp/dessertbee/community/review/service/ReviewService.java
> 203
> 커뮤니티 리뷰 imageindex로 이미지 매핑하던걸 imageUuid로 수정
=> [FIX] 커뮤니티 리뷰 uuid로 수정

src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/community/mate/service/SavedMateService.java, src/main/java/org/swyp/dessertbee/community/review/controller/SavedReviewController.java, src/main/java/org/swyp/dessertbee/community/review/repository/ReviewRepository.java, src/main/java/org/swyp/dessertbee/community/review/repository/SavedReviewRepository.java, src/main/java/org/swyp/dessertbee/community/review/service/ReviewService.java, src/main/java/org/swyp/dessertbee/community/review/service/SavedReviewService.java
> 210
> 커뮤니티 리뷰 북마크 crud api 구현
=> [Feature] 커뮤니티 리뷰 북마크 crud api 구현 

src/main/java/org/swyp/dessertbee/config/SwaggerConfig.java, src/main/resources/application-prod.yml
#215 
- 스웨거 문서에서 CORS에러로 인해 실행이 불가능한 상황 해결
참고 글 
https://kwakscoding.tistory.com/49
=> [FIX & DOCS]: swagger Failed to fetch 오류 해결

.github/workflows/deploy.yml, docker-compose.yml, nginx/conf/default.conf.template, nginx/nginx.conf, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml, src/main/resources/application-release.yml, src/main/resources/application.yml
#232 
- Nginx 설정을 도커 컨테이너로 관리
- 템플릿 기반의 환경별 설정 적용
- 서버 이름을 환경변수로 동적 관리
- 브랜치별 독립적인 배포 환경 구성 (main/release)
- 환경별 다른 호스트 및 설정 사용
- SSL 인증서 자동 발급 및 관리
=> [CHORE] 릴리즈 서버 생성, 엔진엑스 도커 컨테이너로 관리

src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
- /swagger-ui, /api-docs 등은 아예 JWT 필터를 거치지 않도록 설정
- shouldNotFilter에 스웨거 관련 경로 예외 처리
=> chore : swagger경로 shouldNotFilter에 추가

src/main/java/org/swyp/dessertbee/common/controller/SearchController.java, src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java, src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/request/BaseStoreRequest.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/BreakTimeResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/HolidayResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/OperatingHourResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java, src/main/java/org/swyp/dessertbee/store/store/entity/RegularClosureType.java, src/main/java/org/swyp/dessertbee/store/store/entity/Store.java, src/main/java/org/swyp/dessertbee/store/store/entity/StoreBreakTime.java, src/main/java/org/swyp/dessertbee/store/store/entity/StoreOperatingHour.java, src/main/java/org/swyp/dessertbee/store/store/entity/StoreStatistics.java, src/main/java/org/swyp/dessertbee/store/store/repository/SavedStoreRepository.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreBreakTimeRepository.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreOperatingHourRepository.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreStatisticsRepository.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreTagRelationRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
> #248 
> 휴게시간 BreakTime 테이블 추가
> 휴무주기 RegularClosureType Enum 추가
> 가게 통계 deleted_At 설정 및 soft delete (트렌드 리포트를 위해 삭제된 통계도 남겨두도록)
> 가게 삭제 전 연관 데이터 삭제 로직 추가 (외래키 X)
> 공지 notice 컬럼 제거 (별도 테이블로 관리할 예정)
> Swagger 문서 운영시간 스키마 정의
> Swagger 문서 완성된(연결 가능한) AP에 completed 표시
=> [FIX] 가게 운영시간 관련 리팩토링 +)기타 리팩토링

src/main/java/org/swyp/dessertbee/common/controller/SearchController.java, src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java, src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java
> ApiResponse 잘못된 부분 수정 , 누락된 부분 추가
=> Merge dev into release (2) (2025-04-03)

src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
> dev -> release 긴급 병합
> ApiResponse content 긴급 수정 (반경 내 가게 조회 단일->List 응답값)
=> Merge dev into release (3) (2025-04-03)

src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreMapResponse.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
=> Merge dev into release (4) (2025-04-03)

src/main/java/org/swyp/dessertbee/store/menu/dto/request/MenuCreateRequest.java, src/main/java/org/swyp/dessertbee/store/menu/dto/response/MenuResponse.java, src/main/java/org/swyp/dessertbee/store/review/dto/response/StoreReviewResponse.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/request/BaseStoreRequest.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/BreakTimeResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/HolidayResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/OperatingHourResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/SavedStoreResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreListLocationResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreMapResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreSummaryResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/UserStoreListResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/UserStoreListSimpleResponse.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
=> [DOCS] 응답값 nullable 여부 추가

src/main/java/org/swyp/dessertbee/common/dto/PopularSearchResponse.java, src/main/java/org/swyp/dessertbee/common/dto/PopularSearchesList.java, src/main/java/org/swyp/dessertbee/common/dto/UserSearchHistoryDto.java
=> Merge dev into release (2025-04-06)

src/main/java/org/swyp/dessertbee/store/store/dto/request/StoreCreateRequest.java
=> Merge dev into release (2025-04-07)

.github/workflows/deploy.yml, nginx/conf/default.conf.template
#300 
워크 플로우에 설정 파일을 덮어쓰기할 수 있도록 설정해두었습니다.
=> [FIX] 워크플로우에 설정파일 덮어쓰기 옵션 활성화

src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateResponse.java
=> Merge dev into release (2025-04-13)

src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
=> Merge dev into release (2) (2025-04-13)

src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
=> Merge dev into release (2) (2025-04-14)

src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
=> Merge dev into release (3) (2025-04-14)

src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreShortInfoResponse.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
=> Merge dev into release (4) (2025-04-14)

src/main/java/org/swyp/dessertbee/store/store/repository/StoreTopTagRepository.java
=> Merge dev into release (5) (2025-04-14)

src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreInfoResponse.java, src/main/java/org/swyp/dessertbee/store/store/repository/StoreTagRelationRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
=> Merge dev into release (6) (2025-04-14)

src/main/java/org/swyp/dessertbee/store/store/repository/StoreTagRelationRepository.java
=> Merge dev into release (7) (2025-04-13)

src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
=> Merge dev into release (8) (2025-04-13)

src/main/java/org/swyp/dessertbee/statistics/store/entity/StoreStatistics.java, src/main/java/org/swyp/dessertbee/store/coupon/controller/CouponController.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/CouponRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponCondition/AmountConditionRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponCondition/CustomConditionRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponCondition/ExclusiveConditionRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponCondition/TimeDayConditionRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponType/DiscountCouponRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponType/GiftCouponRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/CouponResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/AmountConditionResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/CustomConditionResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/ExclusiveConditionResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/TimeDayConditionResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponType/DiscountCouponResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponType/GiftCouponResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/entity/Coupon.java, src/main/java/org/swyp/dessertbee/store/store/entity/Store.java, src/main/java/org/swyp/dessertbee/user/coupon/controller/UserCouponController.java, src/main/java/org/swyp/dessertbee/user/coupon/dto/request/IssueCouponRequest.java, src/main/java/org/swyp/dessertbee/user/coupon/dto/request/UseCouponRequest.java, src/main/java/org/swyp/dessertbee/user/coupon/dto/response/CouponUsageStatusResponse.java, src/main/java/org/swyp/dessertbee/user/coupon/dto/response/IssuedCouponResponse.java, src/main/java/org/swyp/dessertbee/user/coupon/dto/response/UsedCouponResponse.java, src/main/java/org/swyp/dessertbee/user/coupon/dto/response/UserCouponDetailResponse.java, src/main/java/org/swyp/dessertbee/user/coupon/entity/UserCoupon.java
> 277
> 쿠폰 기능 스웨거 문서 작업
> 디폴트 값 지정한 필드에 @Builder.Default 
> 상속받은 dto 클래스에 @EqualsAndHashCode(callSuper = false)
=> 쿠폰 스웨거 문서 작업 및 어노테이션 설정 

src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreInfoResponse.java, src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreTagResponse.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
=> Merge dev into release (2025-04-16)

src/main/java/org/swyp/dessertbee/store/coupon/dto/request/CouponRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponCondition/AmountConditionRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponCondition/CustomConditionRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponCondition/ExclusiveConditionRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponCondition/TimeDayConditionRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponType/DiscountCouponRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/couponType/GiftCouponRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/CouponResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/AmountConditionResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/CustomConditionResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/ExclusiveConditionResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/TimeDayConditionResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponType/DiscountCouponResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponType/GiftCouponResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/service/CouponServiceImpl.java, src/main/java/org/swyp/dessertbee/user/coupon/dto/response/CouponUsageStatusResponse.java, src/main/java/org/swyp/dessertbee/user/coupon/dto/response/IssuedCouponResponse.java, src/main/java/org/swyp/dessertbee/user/coupon/dto/response/UsedCouponResponse.java, src/main/java/org/swyp/dessertbee/user/coupon/dto/response/UserCouponDetailResponse.java
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> 277 feature coupon

src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/community/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/community/mate/controller/MateReplyController.java, src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateAppReplyCreateRequest.java, src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateReplyCreateRequest.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateAppReplyPageResponse.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateAppReplyResponse.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateReplyPageBaseResponse.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateReplyPageResponse.java, src/main/java/org/swyp/dessertbee/community/mate/entity/MateReply.java, src/main/java/org/swyp/dessertbee/community/mate/exception/MateExceptions.java, src/main/java/org/swyp/dessertbee/community/mate/repository/MateReplyRepository.java, src/main/java/org/swyp/dessertbee/community/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyService.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyServiceImpl.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
> 309
> 디저트메이트 대댓글 기능(앱 한정)
> 디저트메이트 모집중, 모집완료 필터링 기능 추가 (웹,앱 둘다)
=> [Feature] 디저트메이트 대댓글 기능(앱 한정)

src/main/java/org/swyp/dessertbee/config/TestAccountInitializer.java, src/main/java/org/swyp/dessertbee/statistics/common/scheduler/StoreStatisticsScheduler.java, src/main/java/org/swyp/dessertbee/statistics/store/entity/CouponUseLog.java, src/main/java/org/swyp/dessertbee/statistics/store/entity/StoreStatistics.java, src/main/java/org/swyp/dessertbee/statistics/store/entity/StoreStatisticsSummary.java, src/main/java/org/swyp/dessertbee/statistics/store/entity/enums/PeriodType.java, src/main/java/org/swyp/dessertbee/statistics/store/event/CouponUseEvent.java, src/main/java/org/swyp/dessertbee/statistics/store/event/handler/CouponUseLogEventHandler.java, src/main/java/org/swyp/dessertbee/statistics/store/repostiory/CouponUseLogRepository.java, src/main/java/org/swyp/dessertbee/statistics/store/repostiory/StoreStatisticsRepository.java, src/main/java/org/swyp/dessertbee/statistics/store/repostiory/StoreStatisticsSummaryRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java, src/main/java/org/swyp/dessertbee/user/coupon/service/UserCouponServiceImpl.java
=> [MERGE] DEV To RELEASE server (쿠폰 로그, 가게 통계, 테스트 계정)

src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java
> #362 
> 빠진 예외코드를 Swagger문서에 추가했습니다
=> [DOCS] 예외코드 Swagger문서에 추가

src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java, src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java, src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
=> [MERGE] merge dev into release (2025-04-28)

src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateAppReplyResponse.java, src/main/java/org/swyp/dessertbee/community/mate/repository/MateMemberRepository.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateMemberServiceImpl.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyServiceImpl.java
> 360
> 디저트메이트 댓글 필드에 mateMemberGrade 추가
> 해당 멤버가 아닌 예외처리가 사용자가 없습니다 라는 예외가 발생되는 중이라 수정
=> mateMemberGrade 필드 추가 및 예외처리 수정

src/main/java/org/swyp/dessertbee/store/saved/repository/SavedStoreRepository.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreSupportServiceImpl.java
> #54
> 유저 가게 저장 여부 확인 시 단건 조회에서 모두 조회로 변경하여 bug fix
=> [FIX] 유저 가게 저장 여부 확인 시 단건 조회에서 모두 조회로 변경

src/main/java/org/swyp/dessertbee/store/preference/repository/StoreTopTagRepository.java
=> [MERGE] merge dev into release (2025-04-29) (2)

src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java, src/main/java/org/swyp/dessertbee/community/mate/service/SavedMateServiceImpl.java
> 
> 디저트메이트 생성자 예외처리 버그수정 dev에 바로 올린 코드 release로 병합
>
=> 디저트메이트 생성자 예외처리 버그수정

src/main/java/org/swyp/dessertbee/community/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
>  392
> 디저트메이트 repository 오류 수정 후 dev 에서 바로 release로 병합
=> 디저트메이트 repository 오류 수정

src/main/java/org/swyp/dessertbee/common/service/ImageService.java, src/main/java/org/swyp/dessertbee/store/store/handler/StoreImageHandlerImpl.java
> #384 
> deleteImageId 타입 오류 해결
=> [FIX] 가게 이미지 삭제 오류 해결

src/main/java/org/swyp/dessertbee/community/mate/repository/MateRepository.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
=> [MERGE] merge dev into release (2025-05-05)

src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java
> 메뉴 수정 파라미터 요청 @RequestPart로 변경
=> [MERGE] merge dev into release (2025-05-07)

src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java, src/main/java/org/swyp/dessertbee/store/menu/service/MenuService.java, src/main/java/org/swyp/dessertbee/store/menu/service/MenuServiceImpl.java
=> [MERGE] merge dev into release (2025-05-07) (2)

src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java
=> [MERGE] merge dev into release

src/main/java/org/swyp/dessertbee/common/dto/ReportRequest.java, src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java, src/main/java/org/swyp/dessertbee/community/mate/controller/MateController.java, src/main/java/org/swyp/dessertbee/community/mate/controller/MateReplyController.java, src/main/java/org/swyp/dessertbee/community/mate/exception/MateExceptions.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyService.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyServiceImpl.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateService.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java, src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java, src/main/java/org/swyp/dessertbee/store/review/entity/StoreReviewReport.java, src/main/java/org/swyp/dessertbee/store/review/exception/StoreReviewExceptions.java, src/main/java/org/swyp/dessertbee/store/review/repository/StoreReviewReportRepository.java, src/main/java/org/swyp/dessertbee/store/review/repository/StoreReviewRepository.java, src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java, src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java, src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
=> [Feature]가게 한줄 리뷰 신고 기능 api 구현

src/main/java/org/swyp/dessertbee/store/coupon/controller/CouponController.java, src/main/java/org/swyp/dessertbee/store/coupon/dto/request/CouponRequest.java, src/main/java/org/swyp/dessertbee/store/coupon/service/CouponService.java, src/main/java/org/swyp/dessertbee/store/coupon/service/CouponServiceImpl.java
> 403
> 쿠폰 생성, 쿠폰 수정, 쿠폰 삭제에 대해 StoreUuid 를 request body -> pathvariable 로 변경
=> [REFACTOR] 쿠폰 생성 endpoint 변경

src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/CouponConditionResponse.java
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> fix : couponConditionType 반환오류 수정

src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/CouponConditionResponse.java
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> Dev -> Release

src/main/java/org/swyp/dessertbee/store/coupon/dto/response/couponCondition/CouponConditionResponse.java, src/main/java/org/swyp/dessertbee/store/coupon/entity/Coupon.java
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> fix : EXCLUSIVE 타입 오류 수정

src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java, src/main/java/org/swyp/dessertbee/community/mate/service/SavedMateServiceImpl.java
> 418
> 디저트메이트 blockedByAuthorYn 필드 추가
=> 디저트메이트 blockedByAuthorYn 필드 추가

src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateAcceptRequest.java, src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateAppReplyCreateRequest.java, src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateBannedRequest.java, src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateCreateRequest.java, src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateRejectRequest.java, src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateReplyCreateRequest.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateAppReplyPageResponse.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateAppReplyResponse.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateDetailResponse.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateMemberResponse.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateReplyPageResponse.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateReplyResponse.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateReportResponse.java, src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateResponse.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyServiceImpl.java, src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
> 427
> 디저트메이트 댓글에 blockedByAuthorYn 필드 추가해서 차단 유무 확인
=> [Feature] 디저트메이트 댓글 blockedByAuthorYn 필드 추가

src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
=> [CHORE] currentUser null 체크 추가

src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
=> [MERGE] merge dev into release (2025-05-19)

scripts/health-check.sh, src/main/java/org/swyp/dessertbee/config/HealthController.java, src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
- 헬스체크 스크립트의 docker-compose ps 파싱 로직 개선
- Redis 헬스체크에서 docker-compose exec 무한 대기 문제 해결 (docker exec 사용)
- 컨테이너 상태 판단 로직 수정 (Up 상태 정확 감지)
- 모든 서비스 헬스체크 성공률 개선 (3/3 서비스 정상)
=> fix: 배포 시 헬스체크 파싱 오류 및 무한 대기 문제 해결

src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
> 464
> 디저트메이트 수정 시 장소 예외처리 추가
=> [BUG] 디저트메이트 수정 시 장소 예외처리 추가

src/main/java/org/swyp/dessertbee/community/mate/service/MateMemberServiceImpl.java
> 463
> 디저트메이트 자발적으로 나간 사람 인원 줄어들지 않는 버그 수정
=> [BUG] 디저트메이트 나간 사람 인원 줄어들지 않는 버그 수정

src/main/java/org/swyp/dessertbee/common/controller/OptimizationTestController.java, src/main/java/org/swyp/dessertbee/common/controller/PerformanceTestController.java, src/main/java/org/swyp/dessertbee/common/profiler/PerformanceProfiler.java, src/main/java/org/swyp/dessertbee/common/repository/ImageRepository.java, src/main/java/org/swyp/dessertbee/common/service/ImageService.java, src/main/java/org/swyp/dessertbee/config/SecurityConfig.java, src/main/java/org/swyp/dessertbee/store/review/repository/StoreReviewRepository.java, src/main/java/org/swyp/dessertbee/store/schedule/dto/BreakTimeResponse.java, src/main/java/org/swyp/dessertbee/store/schedule/dto/HolidayResponse.java, src/main/java/org/swyp/dessertbee/store/schedule/dto/OperatingHourResponse.java, src/main/java/org/swyp/dessertbee/store/schedule/repository/StoreBreakTimeRepository.java, src/main/java/org/swyp/dessertbee/store/schedule/repository/StoreHolidayRepository.java, src/main/java/org/swyp/dessertbee/store/schedule/repository/StoreOperatingHourRepository.java, src/main/java/org/swyp/dessertbee/store/schedule/service/StoreScheduleService.java, src/main/java/org/swyp/dessertbee/store/schedule/service/StoreScheduleServiceImpl.java, src/main/java/org/swyp/dessertbee/store/store/handler/StoreImageHandler.java, src/main/java/org/swyp/dessertbee/store/store/handler/StoreImageHandlerImpl.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java, src/main/java/org/swyp/dessertbee/store/tag/repository/StoreTagRelationRepository.java, src/main/java/org/swyp/dessertbee/store/tag/service/StoreTagService.java, src/main/java/org/swyp/dessertbee/store/tag/service/StoreTagServiceImpl.java
> 가게 조회(이미지 포함) 성능 개선 및 테스트 추가
=> [MERGE] merge dev into release (2025-06-26)

src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java, src/main/java/org/swyp/dessertbee/community/review/service/ReviewService.java, src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java, src/main/java/org/swyp/dessertbee/store/saved/service/UserStoreServiceImpl.java, src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java, src/main/java/org/swyp/dessertbee/user/coupon/service/UserCouponServiceImpl.java
> DEV->RELEASE 병합
> 트랜잭션 커밋 이전 비동기 이벤트 처리 이슈 해결
> 통계 로그 수집 이벤트 정상 처리
=> [MERGE] DEV->RELEASE (2025/07/14)
